config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    collection { post :import }
  end

  resources :datasets do
    collection { post :import }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dataset.rb
class Dataset < ApplicationRecord
  belongs_to :user

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      dataset = self.find_by(id: row["ID"]) || new
      dataset.label = row["Label"]
      dataset.user_id = row["House"]
      dataset.year = row["Year"]
      dataset.month = row["Month"]
      dataset.temperature = row["Temperature"]
      dataset.daylight = row["Daylight"]
      dataset.energy_production = row["EnergyProduction"]

      # dataset.attributes = row.to_hash.slice(*updatable_attributes)
      dataset.save!
    end
  end

  def self.month_energies_average
    self.joins(:user).group(:month).average(:energy_production)
  end

  def self.city_daylight
    self.joins(:user).group(:city).average(:daylight)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dataset
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = find_by(id: row["ID"]) || new
      user.first_name = row["Firstname"]
      user.last_name = row["Lastname"]
      user.city = row["City"]
      user.num_of_people = row["num_of_people"]
      user.has_child = row["has_child"]

      # user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  def index
    @datasets = Dataset.all
  end

  def import
    Dataset.import(params[:fileupload][:file])
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @datasets = Dataset.all
    @chart_energies = Dataset.month_energies_average
    @num_people_av = User.average(:num_of_people)
    @city_daylight = Dataset.city_daylight
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def import
    User.import(params[:fileupload][:file])
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/datasets/index.html.erb
<div class="container mx-auto">
  <div class="row mt-3">
    <div class="col-6">
      <%= form_tag(import_datasets_path, method: :post, multipart: true) do %>
        <h2>データの追加</h2>
        <%= file_field :fileupload, :file %>
        <%= submit_tag "インポート" %>
      <% end %>
    </div>
    <div class="col-6">
      <button class="btn btn-warning mt-3"><%= link_to "Topページへ",  root_path %></button><br>
      <button class="btn btn-warning mt-3"><%= link_to "顧客登録・一覧へ",  users_path %></button>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-hover">
    <h2 class="mt-5">個別データ</h2>
    <thead>
      <tr>
        <th>ユーザー番号</th>
        <th>年</th>
        <th>月</th>
        <th>気温</th>
        <th>日照時間</th>
        <th>生産量</th>
      </tr>
    </thead>
    <tbody>
      <% @datasets.each do |dataset| %>
        <tr>
          <td><%= dataset.user_id %></td>
          <td><%= dataset.year %></td>
          <td><%= dataset.month %></td>
          <td><%= dataset.temperature %></td>
          <td><%= dataset.daylight %></td>
          <td><%= dataset.energy_production %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnergyProduction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container mt-5 text-center">
  <h1>家庭における電気生産量</h1>
  <div class="row mt-3">
    <div class="col-6 text-right mt-5">
      <img src="/assets/quokka.png" alt="クウォッカのイラスト" class="w-25">
    </div>
    <div class="col-6 text-left mt-5">
      <button class="btn btn-warning mt-3"><%= link_to "データ登録・一覧へ", datasets_path %></button><br>
      <button class="btn btn-warning mt-3"><%= link_to "顧客登録・一覧へ",  users_path %></button>
    </div>
  </div>

  <div class="first-chart-area mt-5">
    <div class="title">
      <p>三都市の平均電気生産量（/月）</p>
      <small>イギリスの１人あたりの平均電気消費量：413kwh/月</small><br>
      <small>世帯ごとの平均人数：<%= @num_people_av %></small>
    </div>
    <div class="chart col-8 mx-auto mt-2">
      <%= line_chart @chart_energies, xtitle: "月", ytitle: "生産量", width: "600px", height: "200px" %>
    </div>
  </div>

  <div class="second-chart-area mt-5">
    <div class="title">
      <p>三都市の日照時間比較（/月）</p>
    </div>
    <div class="chart col-8 mx-auto mt-2">
      <%= column_chart @city_daylight %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mx-auto">
  <div class="row mt-3">
    <div class="col-6">
      <%= form_tag(import_users_path, method: :post, multipart: true) do %>
        <h2>顧客の登録</h2>
        <%= file_field :fileupload, :file %>
        <%= submit_tag "インポート" %>
      <% end %>
    </div>
    <div class="col-6">
      <button class="btn btn-warning mt-3"><%= link_to "Topページへ", root_path %></button><br>
      <button class="btn btn-warning mt-3"><%= link_to "データ登録・一覧へ", datasets_path %></button>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-hover">
    <h2 class="mt-5">顧客情報</h2>
    <thead>
      <tr>
        <th>ID</th>
        <th>姓</th>
        <th>名</th>
        <th>都市</th>
        <th>家族人数</th>
        <th>子供</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.city %></td>
          <td><%= user.num_of_people %></td>
          <td><%= user.has_child %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>